apiVersion: v1
kind: Service
metadata:
  name: stg-total-public-api-service
  labels:
    app: stg-total-public-api
spec:
  selector:
    app: stg-total-public-api
  ports:
    - port: 3000
      protocol: TCP
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: stg-total-public-api-ac
  labels:
    app: stg-total-public-api
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: stg-total-public-api-deployment
  labels:
    app: stg-total-public-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: stg-total-public-api
  template:
    metadata:
      labels:
        app: stg-total-public-api
    spec:
      serviceAccountName: stg-total-public-api-ac
      containers:
        - name: stg-total-public-api
          image: 123123.dkr.ecr.ap-northeast-2.amazonaws.com/total-public-api:13
          ports:
            - containerPort: 3000
          resources:
            limits:
              cpu: "1"
              memory: 800Mi
              ephemeral-storage: "800Mi"
            requests:
              cpu: 200m
              memory: 128Mi
              ephemeral-storage: "128Mi"