jwt:
  secret: testsm

datasource:
  driverName: mysql
  host: localhost
  port: 3306
  database: testsm
  username: testsm
  password: testsm
  charset: utf8mb4
  loc: Asia/Seoul
  logging: true
  maxconn: 1
